### ISSUE TITLE
GitLab now has a pages API

### ISSUE THREAD

**Issue by lupine** [rolodato/gitlab-letsencrypt#30]
Hi there,

Just wanted to note that GitLab 10.2 will ship with a Pages API, which should meet the needs of this project! See https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/13917 for the implementation.

**Comment by rolodato** [comment]
This is great news! When it's release I'd gladly accept PRs for a new version, or work on it myself if I can find the time.

**Comment by To1ne** [comment]
Pinging this issue again, hoping it will gain some traction.

**Comment by rolodato** [comment]
@To1ne I didn't realize that GitLab had already released this API on their public instance. Thanks for the heads up, I plan on working on this soon.

**Comment by travismiller** [comment]
@rolodato I just finished a prototype today and hope to have a pull request in tomorrow! 😁

**Comment by rolodato** [comment]
Released 3.0.0 with support for full automation. I took the opportunity to make some breaking changes, so if you are already using `gitlab-le` please [check the CHANGELOG](https://github.com/rolodato/gitlab-letsencrypt/blob/master/CHANGELOG.markdown). Otherwise just follow the README as usual.

Many thanks to @travismiller for your contribution!
