### ISSUE TITLE
EHOSTUNREACH error

### ISSUE THREAD

**Issue by rffontenelle** [rolodato/gitlab-letsencrypt#42]
When trying to download and install version 3.1.0 using the command line

>  $ npm install -g --user root --prefix pkg/usr --cache src/npm-cache gitlab-letsencrypt@3.1.0

I get the following error output:

> npm ERR! code EHOSTUNREACH
> npm ERR! errno EHOSTUNREACH
> npm ERR! request to https://git.daplie.com/rolodato/le-acme-core/repository/archive.tar.gz failed, reason: connect EHOSTUNREACH 23.228.168.108:443
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /path/to/date-hour-debug.log

Using web browser to access the above URL gets me "ERR_ADDRESS_UNREACHABLE".

**Comment by rolodato** [comment]
I've contacted someone at Daplie to see if they can get their Git server up and running again. If it's not up later today, I'll set up a mirror somewhere else as a workaround. Thanks for reporting this!

**Comment by leipert** [comment]
Why not publish it under `@rolodato/le-acme-core` ?

**Comment by rolodato** [comment]
@leipert I don't have a local mirror of the repository, unfortunately. I'm at work now but when I can I'll try to fix this.

**Comment by rolodato** [comment]
Sorry for the trouble folks, I've published 3.1.1 which points to a backup fork I've made of le-acme-core. Unfortunately I only had my local node_modules copy which doesn't include the full repository history, so that seems to have been lost forever unless someone had cloned the repository or someone from Daplie can give us a copy.
